### ISSUE TITLE
errors when running GrammalecteCheck

### ISSUE THREAD

**Issue by arnauldb** [dpelle/vim-Grammalecte#14]
Hello,

I installed Grammalecte for vim, but I have these errors while running 
`GrammalecteCheck`

> Error detected while processing function <SNR>96_GrammalecteCheck:
> line   28:
> Command [python3 /home/arnauld/Desktop/docsdesktop/Grammalecte-fr-v1.2/grammalecte-cli.py -f /tmp/vKg381O/6 -roff apostrophe_typograp
> hique apostrophe_typographique_après_t espaces_début_ligne espaces_milieu_ligne espaces_fin_de_ligne esp_début_ligne esp_milieu_ligne
>  esp_fin_ligne esp_mélangés2 typo_points_suspension1 typo_tiret_incise nbsp_avant_double_ponctuation nbsp_avant_deux_points nbsp_aprè
> s_chevrons_ouvrants nbsp_avant_chevrons_fermants1 unit_nbsp_avant_unités1 unit_nbsp_avant_unités2 unit_nbsp_avant_unités3 -j -cl -owe
>  -ctx 2> /tmp/vKg381O/7] failed with error: 1
> line   31:
> ['Traceback (most recent call last):', '  File "/home/arnauld/Desktop/docsdesktop/Grammalecte-fr-v1.2/grammalecte-cli.py", line 298, 
> in <module>', '    main()', '  File "/home/arnauld/Desktop/docsdesktop/Grammalecte-fr-v1.2/grammalecte-cli.py", line 200, in main', '
>     output(sText, hDst)', '  File "/home/arnauld/Desktop/docsdesktop/Grammalecte-fr-v1.2/grammalecte-cli.py", line 89, in output', ' 
>    echo(sText, end="")', '  File "/home/arnauld/Desktop/docsdesktop/Grammalecte-fr-v1.2/grammalecte/graphspell/echo.py", line 27, in 
> echo', '    print(obj, sep=sep, end=end, file=file, flush=flush)', 'UnicodeEncodeError: ''ascii'' codec can''t encode character ''\xa
> 0'' in position 306: ordinal not in range(128)']

In my .vimrc I added:
`let g:grammalecte_cli_py='/home/arnauld/Desktop/docsdesktop/Grammalecte-fr-v1.2/grammalecte-cli.py'`

I installed the plugin manually.

Thank you for any help.

**Comment by Stekache** [comment]
Hello. Thanks for your plugin. Got the same problem as arnauldb, fixed #23
