### ISSUE TITLE
Is the plugin dead?

### ISSUE THREAD

**Issue by ghost** [dpelle/vim-Grammalecte#21]
The plugin does not have any update since a long long time.

Many things have change in `grammalect cli`. The main script is now called `grammar_check.py`.

So is the plugin a abandoned software?

**Comment by tarikgraba** [comment]
As of version 1.7 (the last stable version) available here:
https://grammalecte.net/grammalecte/zip/Grammalecte-fr-v1.7.0.zip

The `grammalecte-cli.py` script is still here at the root of the zip.

**Comment by ghost** [comment]
Ok found on the latest (1.8.0) version.

May be I misinstalled grammelecte:

`python3.7 setup install`

I have a strange behavior calling :grammacheck:

```
 Erreur détectée en traitant function <SNR>22_GrammalecteCheck :
ligne   28 :
Command [python3 /usr/local/bin/grammalecte-cli.py -f /tmp/vuErL0m/0 -roff typo_tiret_incise nbsp_avant_double_ponctuation nbsp_avant_deux_p
oints nbsp_après_chevrons_ouvrants nbsp_avant_chevrons_fermants1 unit_nbsp_avant_unités1 unit_nbsp_avant_unités2 unit_nbsp_avant_unités3 apo
strophe_typographique apostrophe_typographique_après_t -j -cl -owe -ctx 2> /tmp/vuErL0m/1] failed with error: 1
ligne   31 :
['Traceback (most recent call last):', '  File "/usr/local/bin/grammalecte-cli.py", line 4, in <module>', '    __import__(''pkg_resources'')
.run_script(''Grammalecte-fr==1.8.0'', ''grammalecte-cli.py'')', '  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py",
 line 666, in run_script', '    self.require(requires)[0].run_script(script_name, ns)', '  File "/usr/local/lib/python3.7/site-packages/pkg_
resources/__init__.py", line 1453, in run_script', '    .format(**locals()),', 'pkg_resources.ResolutionError: Script ''scripts/grammalecte-
cli.py'' not found in metadata at ''/usr/local/lib/python3.7/site-packages/Grammalecte_fr-1.8.0-py3.7.egg-info''']
```

Even running `grammalecte-cli.py` alone run into errors:
```
/usr/local/bin/grammalecte-cli.py
Traceback (most recent call last):
  File "/usr/local/bin/grammalecte-cli.py", line 4, in <module>
    __import__('pkg_resources').run_script('Grammalecte-fr==1.8.0', 'grammalecte-cli.py')
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/grammalecte-cli.py' not found in metadata at '/usr/local/lib/python3.7/site-packages/Grammalecte_fr-1.8.0-py3.7.egg-info'
```

What's going wrong?

Thanks for your help or advice.

**Comment by dpelle** [comment]
@jfoucry wrote:

> So is the plugin a abandoned software?

It's not dead, but I neglected it with lack of time and reduced interest.
But I have just merged a few PR and made other doc updates.

**Comment by dpelle** [comment]
@jfoucry wrote:

> I have a strange behavior calling :grammacheck:

I don't see this error.  But I installed it differently.  I did:
```
  $ mkdir ~/Grammalecte-fr-v1.8.0
  $ cd ~/Grammalecte-fr-v1.8.0
  $ wget https://grammalecte.net/grammalecte/zip/Grammalecte-fr-v1.8.0.zip
  $ unzip Grammalecte-fr-v1.8.0.zip
```
Then I put this in my `~/.vimrc`:
```
:let g:grammalecte_cli_py='$HOME/Grammalecte-fr-v1.8.0/grammalecte-cli.py'
```
And the plugin works fine for me on Linux. Does this work for you too?

**Comment by ghost** [comment]
It works \o/

Thanks for you help and your job.
